### ISSUE TITLE
Cloudflared pods should reload when configmap changed

### ISSUE THREAD

**Issue by locmai** [khuedoan/charts#2]
Having an issue with cloudflared workloads didn't reload new config when configmap updated. Should we add a sidecar to do the work?

**Comment by khuedoan** [comment]
I think this should be enough https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

**Comment by khuedoan** [comment]
Fixed with 1327011a25e7ff1f9ca5fbdd9d8bb45840f6afd6

**Comment by locmai** [comment]
Thank you!
